In [1]:
from platform import python_version

print(python_version())

3.10.12


In [2]:
import pyreadr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


import numpy as np
import scipy.stats as stats
from scipy.linalg import eigh

In [3]:
# constants
dataset_dir = "./datasets/TEP/"

In [4]:
def read_r_as_df(file_path):
    result = pyreadr.read_r(file_path) # also works for Rds
    return result[list(result.keys())[0]]

In [5]:
training_fault_free_df = read_r_as_df(f"{dataset_dir}/TEP_FaultFree_Training.RData")

In [6]:
training_fault_free_df.describe()

faultNumber  simulationRun         sample        xmeas_1  \
count     250000.0  250000.000000  250000.000000  250000.000000   
mean           0.0     250.500000     250.500000       0.250482   
std            0.0     144.337567     144.337567       0.030873   
min            0.0       1.000000       1.000000       0.122450   
25%            0.0     125.750000     125.750000       0.229770   
50%            0.0     250.500000     250.500000       0.250510   
75%            0.0     375.250000     375.250000       0.271200   
max            0.0     500.000000     500.000000       0.391740   

             xmeas_2       xmeas_3        xmeas_4        xmeas_5  \
count  250000.000000  250000.00000  250000.000000  250000.000000   
mean     3663.785706    4508.81979       9.347101      26.902196   
std        34.006357      39.21542       0.085721       0.211485   
min      3511.800000    4336.90000       8.972700      25.951000   
25%      3640.800000    4482.40000       9.289300      26.758000   
50%      3663.700000    4508.80000       9.347100      26.902000   
75%      3686.800000    4535.30000       9.405100      27.046000   
max      3808.400000    4683.70000       9.729800      27.818000   

             xmeas_6        xmeas_7  ...          xmv_2          xmv_3  \
count  250000.000000  250000.000000  ...  250000.000000  250000.000000   
mean       42.337598    2705.037865  ...      53.973668      24.639472   
std         0.218513       7.525596  ...       0.469663       3.037743   
min        41.394000    2672.300000  ...      52.095000      11.977000   
25%        42.188000    2700.100000  ...      53.657000      22.602000   
50%        42.338000    2705.000000  ...      53.974000      24.644000   
75%        42.487000    2710.000000  ...      54.290000      26.674000   
max        43.257000    2739.100000  ...      56.118000      38.351000   

               xmv_4          xmv_5          xmv_6          xmv_7  \
count  250000.000000  250000.000000  250000.000000  250000.000000   
mean       61.298501      22.216644      40.055456      38.098898   
std         1.243805       0.530156       1.526751       2.965266   
min        55.961000      19.749000      33.389000      25.959000   
25%        60.453000      21.864000      39.021000      36.081000   
50%        61.298000      22.217000      40.058000      38.091000   
75%        62.144000      22.568000      41.084000      40.117000   
max        66.443000      24.525000      47.498000      50.729000   

               xmv_8          xmv_9         xmv_10         xmv_11  
count  250000.000000  250000.000000  250000.000000  250000.000000  
mean       46.534295      47.958591      41.104304      18.118706  
std         2.351304       2.716520       0.540817       1.463678  
min        36.937000      36.641000      38.586000      11.705000  
25%        44.931000      46.265000      40.740000      17.130000  
50%        46.530000      47.820000      41.104000      18.119000  
75%        48.140000      49.651000      41.470000      19.111000  
max        56.443000      59.616000      43.930000      24.762000  

[8 rows x 55 columns]

In [7]:

# fig, ax = plt.subplots(13,4,figsize=(30,50))
# 
# cols_names = training_fault_free_df.columns[3:]
# for j in range(1,5):
    # df_train = training_fault_free_df[training_fault_free_df.simulationRun==j].iloc[:,3:]
    # for i in range(df_train.shape[1]):
        # ax.ravel()[i].plot(range(0,500),df_train.iloc[:,i])
        # #df_train.iloc[:,i].plot(ax=ax.ravel()[i]) 
        # ax.ravel()[i].set_title(cols_names[i])
    # #print(j)

In [8]:
# PCA training


In [9]:
X= training_fault_free_df.values[:,3:]
N,m = X.shape


In [10]:
# normalize the data
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X_normalized = (X - X_mean) / X_std

In [11]:
# compute eigen values and eigen vectors
cov_matrix = np.cov(X_normalized, rowvar=False)
eigenvalues, eigenvectors = eigh(cov_matrix)  # Compute eigen decomposition
idx = np.argsort(eigenvalues)[::-1]  # Sort eigenvalues in descending order
eigenvalues, eigenvectors = eigenvalues[idx], eigenvectors[:, idx]

In [12]:
cov_matrix.shape

(52, 52)

In [13]:
result = np.linalg.svd(cov_matrix, full_matrices=False)

In [14]:
result.U

array([[-1.50339762e-01, -1.21564678e-01,  2.13170620e-01, ...,
         2.04323879e-03,  7.72495792e-07,  4.61603542e-07],
       [ 3.54975130e-02,  4.89450389e-02,  3.67322506e-01, ...,
         1.73696373e-04,  1.41499291e-06, -3.36849367e-08],
       [ 1.48533719e-01, -3.32722443e-02, -3.73502743e-02, ...,
         6.91950213e-04, -1.57628452e-08,  6.05638042e-07],
       ...,
       [-9.45763048e-02,  3.80930088e-01, -4.05282516e-02, ...,
         3.67938927e-02,  4.92749173e-06,  3.46641227e-06],
       [ 6.05050890e-02,  1.18612926e-01,  4.23933504e-01, ...,
        -9.76384060e-04, -2.03859385e-07,  5.00322738e-07],
       [ 5.97735359e-03, -1.78076055e-02,  3.52519423e-02, ...,
        -7.05156307e-01,  3.23603484e-06,  3.02249881e-05]])

In [15]:
result.U

array([[-1.50339762e-01, -1.21564678e-01,  2.13170620e-01, ...,
         2.04323879e-03,  7.72495792e-07,  4.61603542e-07],
       [ 3.54975130e-02,  4.89450389e-02,  3.67322506e-01, ...,
         1.73696373e-04,  1.41499291e-06, -3.36849367e-08],
       [ 1.48533719e-01, -3.32722443e-02, -3.73502743e-02, ...,
         6.91950213e-04, -1.57628452e-08,  6.05638042e-07],
       ...,
       [-9.45763048e-02,  3.80930088e-01, -4.05282516e-02, ...,
         3.67938927e-02,  4.92749173e-06,  3.46641227e-06],
       [ 6.05050890e-02,  1.18612926e-01,  4.23933504e-01, ...,
        -9.76384060e-04, -2.03859385e-07,  5.00322738e-07],
       [ 5.97735359e-03, -1.78076055e-02,  3.52519423e-02, ...,
        -7.05156307e-01,  3.23603484e-06,  3.02249881e-05]])

In [16]:
eigenvalues

array([8.01214204e+00, 4.80102770e+00, 2.60949858e+00, 2.05697355e+00,
       1.99995122e+00, 1.95234079e+00, 1.77151045e+00, 1.61320525e+00,
       1.41059479e+00, 1.19763386e+00, 1.15428192e+00, 1.05716890e+00,
       1.03339285e+00, 1.00893201e+00, 1.00190199e+00, 9.89429833e-01,
       9.78238425e-01, 9.71602211e-01, 9.65043949e-01, 9.60612070e-01,
       9.44034908e-01, 9.42140360e-01, 9.28484568e-01, 9.12011415e-01,
       8.94510415e-01, 8.78583175e-01, 8.51001620e-01, 8.38797624e-01,
       7.29769464e-01, 6.95008441e-01, 6.89996673e-01, 6.66671957e-01,
       6.17562955e-01, 5.99041270e-01, 5.77978341e-01, 5.15509525e-01,
       4.69353484e-01, 4.35601184e-01, 3.73708784e-01, 3.36143618e-01,
       2.49675068e-01, 1.78993530e-01, 5.35238147e-02, 4.25699182e-02,
       1.53131710e-02, 8.70418822e-03, 4.90741851e-03, 3.41276974e-03,
       1.59041759e-03, 1.25440281e-04, 4.77980393e-08, 4.57667077e-08])

In [17]:
eigenvectors[:, 0]

array([ 0.15033976, -0.03549751, -0.14853372, -0.05317601, -0.00426865,
       -0.00298932, -0.32841397, -0.04600825, -0.01281236,  0.12955364,
        0.23815949,  0.00860801, -0.32929298,  0.02067484,  0.00832118,
       -0.30888287,  0.00817263,  0.1335795 ,  0.07423738, -0.24798659,
        0.09811677,  0.03958099, -0.06191733,  0.08308756, -0.19203073,
        0.05377129,  0.17939293,  0.06961666, -0.08438927,  0.11691133,
       -0.22200624,  0.06616919,  0.23209561,  0.10539633,  0.18915191,
        0.10047343,  0.00904644,  0.16972143,  0.01312571,  0.02194532,
       -0.01972001, -0.03642925, -0.14735714,  0.15040118, -0.02223652,
       -0.28035392,  0.16354657,  0.00860824,  0.00832145,  0.0945763 ,
       -0.06050509, -0.00597735])

In [18]:
# Select number of principal components (retain 90% variance)
retain_variance = 0.9
explained_variance_ratio = np.cumsum(eigenvalues) / np.sum(eigenvalues)
l = np.argmax(explained_variance_ratio >= retain_variance) + 1  # Number of retained PCs
print(f"PCS components: {l} for {retain_variance} retain variance")


PCS components: 31 for 0.9 retain variance


In [19]:
# Partition Eigenvectors
P_pc = eigenvectors[:, :l]  # Retained PCs
P_res = eigenvectors[:, l:]  # Residual PCs

In [20]:
# Compute SPE threshold (J_th,SPE)
theta_1 = np.sum(eigenvalues[l:])
theta_2 = np.sum(eigenvalues[l:] ** 2)
theta_3 = np.sum(eigenvalues[l:] ** 3)
h0 = 1 - (2 * theta_1 * theta_3) / (3 * theta_2 ** 2)
c_alpha = stats.norm.ppf(0.99)  # 99% confidence level
J_th_SPE = theta_1 * (c_alpha * np.sqrt(2 * theta_2 * h0 ** 2 / theta_1) + 1 + (theta_2 * h0 * (h0 - 1)) / (theta_1 ** 2)) ** (1 / h0)

print(f"SPE threshold J_th_SPE = {J_th_SPE}")

SPE threshold J_th_SPE = 29.672565740289073


In [21]:
# Compute T² threshold (J_th,T2)
F_alpha = stats.f.ppf(0.99, l, N - l)
J_th_T2 = (l * (N**2 - 1)) / (N * (N - 1)) * F_alpha
print(f"T2 threshold J_th_T2 = {J_th_T2}")

T2 threshold J_th_T2 = 52.19402469957485


In [22]:
# Online Phase - Detect Faults
def detect_fault(new_sample):
    # Normalize the new sample
    new_sample_norm = (new_sample - X_mean) / X_std

    # Compute SPE
    SPE = new_sample_norm @ P_res @ P_res.T @ new_sample_norm.T

    # Compute T² statistic
    T2 = new_sample_norm @ P_pc @ np.linalg.inv(np.diag(eigenvalues[:l])) @ P_pc.T @ new_sample_norm.T

    # Fault Detection Logic
    if SPE > J_th_SPE or T2 > J_th_T2:
        return False
    return True

In [23]:
import pickle


In [24]:
# save model parameters
model_params = {
    "mean": X_mean,
    "std": X_std,
    "eigenvalues": eigenvalues,
    "P_res": P_res,
    "l": l,
    "P_pc": P_pc,
    "J_th_SPE": J_th_SPE,
    "J_th_T2": J_th_T2
}
with open("pca_predictor_params.pickle", "wb") as f:
    pickle.dump(model_params, f)